//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackupSyncApp.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackupSyncApp.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Sync Application.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable auto backup.
        /// </summary>
        public static string AutoBack_Check {
            get {
                return ResourceManager.GetString("AutoBack_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Btn_AddFolder {
            get {
                return ResourceManager.GetString("Btn_AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose disk.
        /// </summary>
        public static string Btn_ChooseDisk {
            get {
                return ResourceManager.GetString("Btn_ChooseDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear log.
        /// </summary>
        public static string Btn_clearLog {
            get {
                return ResourceManager.GetString("Btn_clearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure....
        /// </summary>
        public static string Btn_ConfigAB {
            get {
                return ResourceManager.GetString("Btn_ConfigAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Backup Now.
        /// </summary>
        public static string Btn_ManualBack {
            get {
                return ResourceManager.GetString("Btn_ManualBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Btn_RemoveFolder {
            get {
                return ResourceManager.GetString("Btn_RemoveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset settings.
        /// </summary>
        public static string Btn_resetSettings {
            get {
                return ResourceManager.GetString("Btn_resetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save log.
        /// </summary>
        public static string Btn_saveLog {
            get {
                return ResourceManager.GetString("Btn_saveLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Files (ZIP).
        /// </summary>
        public static string Chk_ArchiveFiles {
            get {
                return ResourceManager.GetString("Chk_ArchiveFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable reminder.
        /// </summary>
        public static string Chk_EnableReminder {
            get {
                return ResourceManager.GetString("Chk_EnableReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with Windows.
        /// </summary>
        public static string Chk_StartWithWindows {
            get {
                return ResourceManager.GetString("Chk_StartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚖️ Balanced.
        /// </summary>
        public static string CompressionMode_Balanced {
            get {
                return ResourceManager.GetString("CompressionMode_Balanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚡ Fast.
        /// </summary>
        public static string CompressionMode_Fast {
            get {
                return ResourceManager.GetString("CompressionMode_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📦 Maximum.
        /// </summary>
        public static string CompressionMode_Maximum {
            get {
                return ResourceManager.GetString("CompressionMode_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string DayOfWeek_Friday {
            get {
                return ResourceManager.GetString("DayOfWeek_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string DayOfWeek_Monday {
            get {
                return ResourceManager.GetString("DayOfWeek_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string DayOfWeek_Saturday {
            get {
                return ResourceManager.GetString("DayOfWeek_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string DayOfWeek_Sunday {
            get {
                return ResourceManager.GetString("DayOfWeek_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string DayOfWeek_Thursday {
            get {
                return ResourceManager.GetString("DayOfWeek_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string DayOfWeek_Tuesday {
            get {
                return ResourceManager.GetString("DayOfWeek_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string DayOfWeek_Wednesday {
            get {
                return ResourceManager.GetString("DayOfWeek_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose backup target disk.
        /// </summary>
        public static string Dialog_ChooseDisk {
            get {
                return ResourceManager.GetString("Dialog_ChooseDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose source folders | files.
        /// </summary>
        public static string Dialog_ChooseSourceFolder {
            get {
                return ResourceManager.GetString("Dialog_ChooseSourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose external target drive.
        /// </summary>
        public static string Dialog_ChooseUSB {
            get {
                return ResourceManager.GetString("Dialog_ChooseUSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive creation failed: {0}.
        /// </summary>
        public static string Error_ArchiveFailed {
            get {
                return ResourceManager.GetString("Error_ArchiveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No target path specified!.
        /// </summary>
        public static string Error_NoPathChosen {
            get {
                return ResourceManager.GetString("Error_NoPathChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No source folders specified!.
        /// </summary>
        public static string Error_NoSourceGiven {
            get {
                return ResourceManager.GetString("Error_NoSourceGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive settings.
        /// </summary>
        public static string Header_ArchiveSettings {
            get {
                return ResourceManager.GetString("Header_ArchiveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Backup.
        /// </summary>
        public static string Header_AutoBackup {
            get {
                return ResourceManager.GetString("Header_AutoBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Header_AutoBackupDetails {
            get {
                return ResourceManager.GetString("Header_AutoBackupDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-start.
        /// </summary>
        public static string Header_AutoStart {
            get {
                return ResourceManager.GetString("Header_AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder.
        /// </summary>
        public static string Header_BackupReminder {
            get {
                return ResourceManager.GetString("Header_BackupReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language/Язык.
        /// </summary>
        public static string Header_LanguageSettings {
            get {
                return ResourceManager.GetString("Header_LanguageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations Log.
        /// </summary>
        public static string Header_Log {
            get {
                return ResourceManager.GetString("Header_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Backup.
        /// </summary>
        public static string Header_ManualBackup {
            get {
                return ResourceManager.GetString("Header_ManualBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Header_ResetSettings {
            get {
                return ResourceManager.GetString("Header_ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Header_Settings {
            get {
                return ResourceManager.GetString("Header_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source folders.
        /// </summary>
        public static string Header_SourceFolderPanel {
            get {
                return ResourceManager.GetString("Header_SourceFolderPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application will start automatically when Windows boots.
        /// </summary>
        public static string Hint_AutoStart {
            get {
                return ResourceManager.GetString("Hint_AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast = less compression, Maximum = smaller size.
        /// </summary>
        public static string Hint_CompressionMode {
            get {
                return ResourceManager.GetString("Hint_CompressionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language change requires restart.
        /// </summary>
        public static string Hint_LanguageSettings {
            get {
                return ResourceManager.GetString("Hint_LanguageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be notified on the selected day if no backup was done.
        /// </summary>
        public static string Hint_Reminder {
            get {
                return ResourceManager.GetString("Hint_Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder is already added.
        /// </summary>
        public static string Msg_AlreadyAdded {
            get {
                return ResourceManager.GetString("Msg_AlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove folder &apos;{0}&apos; from backup list?.
        /// </summary>
        public static string Msg_ConfirmRemove {
            get {
                return ResourceManager.GetString("Msg_ConfirmRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm folder removal.
        /// </summary>
        public static string Msg_ConfirmRemoveTitle {
            get {
                return ResourceManager.GetString("Msg_ConfirmRemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk configured for auto backup.
        ///Path: {0}
        ///Label: {1}
        ///Type: {2}
        ///Next time you connect this disk, backup will start automatically..
        /// </summary>
        public static string Msg_DiskConfigured {
            get {
                return ResourceManager.GetString("Msg_DiskConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk Configuration.
        /// </summary>
        public static string Msg_DiskConfiguredTitle {
            get {
                return ResourceManager.GetString("Msg_DiskConfiguredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected drive is not ready.
        /// </summary>
        public static string Msg_DriveNotReady {
            get {
                return ResourceManager.GetString("Msg_DriveNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string Msg_Error {
            get {
                return ResourceManager.GetString("Msg_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Msg_ErrorTitle {
            get {
                return ResourceManager.GetString("Msg_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Msg_InfromationTitle {
            get {
                return ResourceManager.GetString("Msg_InfromationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a USB disk or external drive. 
        ///Selected disk type: {0}.
        /// </summary>
        public static string Msg_InvalidDiskType {
            get {
                return ResourceManager.GetString("Msg_InvalidDiskType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid disk type.
        /// </summary>
        public static string Msg_InvalidDiskTypeTitle {
            get {
                return ResourceManager.GetString("Msg_InvalidDiskTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language will be changed after restart.
        /// </summary>
        public static string Msg_LanguageChanged {
            get {
                return ResourceManager.GetString("Msg_LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language change.
        /// </summary>
        public static string Msg_LanguageChangedTitle {
            get {
                return ResourceManager.GetString("Msg_LanguageChangedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Msg_No {
            get {
                return ResourceManager.GetString("Msg_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No folders left to remove from the list.
        /// </summary>
        public static string Msg_NoFolders {
            get {
                return ResourceManager.GetString("Msg_NoFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t done a backup today. Do it now?.
        /// </summary>
        public static string Msg_ReminderClose {
            get {
                return ResourceManager.GetString("Msg_ReminderClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Reminder.
        /// </summary>
        public static string Msg_ReminderCloseTitle {
            get {
                return ResourceManager.GetString("Msg_ReminderCloseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset all settings? This will remove:
        ///- All configured folders
        ///- USB disk settings
        ///- Auto-backup settings
        ///- Reminder settings.
        /// </summary>
        public static string Msg_ResetSettings {
            get {
                return ResourceManager.GetString("Msg_ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset settings.
        /// </summary>
        public static string Msg_ResetSettingsTitle {
            get {
                return ResourceManager.GetString("Msg_ResetSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose disk for backup.
        /// </summary>
        public static string Msg_SelectDisk {
            get {
                return ResourceManager.GetString("Msg_SelectDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder for backup.
        /// </summary>
        public static string Msg_SelectFolder {
            get {
                return ResourceManager.GetString("Msg_SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select USB disk for auto backup .
        /// </summary>
        public static string Msg_SelectUsb {
            get {
                return ResourceManager.GetString("Msg_SelectUsb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting were reseted successfully.
        ///Application restart recommended..
        /// </summary>
        public static string Msg_SettingsReseted {
            get {
                return ResourceManager.GetString("Msg_SettingsReseted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Msg_WarningTitle {
            get {
                return ResourceManager.GetString("Msg_WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Msg_Yes {
            get {
                return ResourceManager.GetString("Msg_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚡Auto Backup.
        /// </summary>
        public static string Nav_autoBack {
            get {
                return ResourceManager.GetString("Nav_autoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        public static string Nav_header {
            get {
                return ResourceManager.GetString("Nav_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📋 Operation log.
        /// </summary>
        public static string Nav_Log {
            get {
                return ResourceManager.GetString("Nav_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📁 Manual Backup.
        /// </summary>
        public static string Nav_manualBack {
            get {
                return ResourceManager.GetString("Nav_manualBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚙️ Settings.
        /// </summary>
        public static string Nav_Settings {
            get {
                return ResourceManager.GetString("Nav_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today is backup day! Don&apos;t forget to backup!.
        /// </summary>
        public static string Reminder_BackupDayArrived {
            get {
                return ResourceManager.GetString("Reminder_BackupDayArrived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string ReminderMode_Daily {
            get {
                return ResourceManager.GetString("ReminderMode_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string ReminderMode_Monthly {
            get {
                return ResourceManager.GetString("ReminderMode_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string ReminderMode_Weekly {
            get {
                return ResourceManager.GetString("ReminderMode_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        public static string ReminderMode_Yearly {
            get {
                return ResourceManager.GetString("ReminderMode_Yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string TrayMenu_Exit {
            get {
                return ResourceManager.GetString("TrayMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string TrayMenu_Open {
            get {
                return ResourceManager.GetString("TrayMenu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto backup completed!.
        /// </summary>
        public static string TrayNotification_AutoBackupComplete {
            get {
                return ResourceManager.GetString("TrayNotification_AutoBackupComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup completed successfully!.
        /// </summary>
        public static string TrayNotification_BackupComplete {
            get {
                return ResourceManager.GetString("TrayNotification_BackupComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup error.
        /// </summary>
        public static string TrayNotification_BackupError {
            get {
                return ResourceManager.GetString("TrayNotification_BackupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files Copied: .
        /// </summary>
        public static string TrayNotification_FilesCopied {
            get {
                return ResourceManager.GetString("TrayNotification_FilesCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup notification.
        /// </summary>
        public static string TrayNotification_Title {
            get {
                return ResourceManager.GetString("TrayNotification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        public static string Tutorial_Button_Done {
            get {
                return ResourceManager.GetString("Tutorial_Button_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next →.
        /// </summary>
        public static string Tutorial_Button_Next {
            get {
                return ResourceManager.GetString("Tutorial_Button_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ← Back.
        /// </summary>
        public static string Tutorial_Button_Prev {
            get {
                return ResourceManager.GetString("Tutorial_Button_Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything is ready!
        ///Now just connect the configured USB drive — and backup will start automatically.
        ///You can always minimize the application to the tray — it will continue to work..
        /// </summary>
        public static string Tutorial_Done_Text {
            get {
                return ResourceManager.GetString("Tutorial_Done_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ You&apos;re all set!.
        /// </summary>
        public static string Tutorial_Done_Title {
            get {
                return ResourceManager.GetString("Tutorial_Done_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Add folders you want to back up
        ///2. Select a USB drive for copying
        ///3. Enable &quot;Auto-backup&quot; option
        ///The application will run in the background and wait for the USB drive to be connected..
        /// </summary>
        public static string Tutorial_How_Text {
            get {
                return ResourceManager.GetString("Tutorial_How_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📁 How it works.
        /// </summary>
        public static string Tutorial_How_Title {
            get {
                return ResourceManager.GetString("Tutorial_How_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackupSyncApp is a simple application for backing up files to USB drives.
        ///It&apos;s designed specifically for inexperienced users — you don&apos;t need to understand complex settings!.
        /// </summary>
        public static string Tutorial_Welcome_Text {
            get {
                return ResourceManager.GetString("Tutorial_Welcome_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👋 Welcome!.
        /// </summary>
        public static string Tutorial_Welcome_Title {
            get {
                return ResourceManager.GetString("Tutorial_Welcome_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackypSyncApp - Tutorial.
        /// </summary>
        public static string Tutorial_WindowTitle {
            get {
                return ResourceManager.GetString("Tutorial_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archiving....
        /// </summary>
        public static string Txt_Archiving {
            get {
                return ResourceManager.GetString("Txt_Archiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔒 Archive password:.
        /// </summary>
        public static string Txt_ArchPasswrd {
            get {
                return ResourceManager.GetString("Txt_ArchPasswrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Path:.
        /// </summary>
        public static string Txt_AutoBackupFullPath {
            get {
                return ResourceManager.GetString("Txt_AutoBackupFullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup copy will be created on this disk.
        /// </summary>
        public static string Txt_BackupHere {
            get {
                return ResourceManager.GetString("Txt_BackupHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode:.
        /// </summary>
        public static string Txt_CompressionMode {
            get {
                return ResourceManager.GetString("Txt_CompressionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying... {0}%.
        /// </summary>
        public static string Txt_Copying {
            get {
                return ResourceManager.GetString("Txt_Copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remembered drive:.
        /// </summary>
        public static string Txt_Current_dsk {
            get {
                return ResourceManager.GetString("Txt_Current_dsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📀 Current drive.
        /// </summary>
        public static string Txt_CurrentVisibleDriveHead {
            get {
                return ResourceManager.GetString("Txt_CurrentVisibleDriveHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Txt_CurrentVisibleDriveNone {
            get {
                return ResourceManager.GetString("Txt_CurrentVisibleDriveNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of month:.
        /// </summary>
        public static string Txt_DayOfMonth {
            get {
                return ResourceManager.GetString("Txt_DayOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of week:.
        /// </summary>
        public static string Txt_DayOfWeek {
            get {
                return ResourceManager.GetString("Txt_DayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk Info.
        /// </summary>
        public static string Txt_DiskInfo {
            get {
                return ResourceManager.GetString("Txt_DiskInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no disk chosen.
        /// </summary>
        public static string Txt_DiskNotChosen {
            get {
                return ResourceManager.GetString("Txt_DiskNotChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last operation time.
        /// </summary>
        public static string Txt_LastOpsTime {
            get {
                return ResourceManager.GetString("Txt_LastOpsTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No password.
        /// </summary>
        public static string Txt_NoPassword {
            get {
                return ResourceManager.GetString("Txt_NoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password set.
        /// </summary>
        public static string Txt_PasswordSet {
            get {
                return ResourceManager.GetString("Txt_PasswordSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Txt_Ready {
            get {
                return ResourceManager.GetString("Txt_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💾 Remembered drive.
        /// </summary>
        public static string Txt_RememberedDriveHead {
            get {
                return ResourceManager.GetString("Txt_RememberedDriveHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not configured.
        /// </summary>
        public static string Txt_RememberedDriveNone {
            get {
                return ResourceManager.GetString("Txt_RememberedDriveNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Date:.
        /// </summary>
        public static string Txt_ReminderDate {
            get {
                return ResourceManager.GetString("Txt_ReminderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency:.
        /// </summary>
        public static string Txt_ReminderFrequency {
            get {
                return ResourceManager.GetString("Txt_ReminderFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (backup in process...).
        /// </summary>
        public static string Txt_Status_DriveCopying {
            get {
                return ResourceManager.GetString("Txt_Status_DriveCopying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Txt_Status_Error {
            get {
                return ResourceManager.GetString("Txt_Status_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (inactive).
        /// </summary>
        public static string Txt_Status_Inactive {
            get {
                return ResourceManager.GetString("Txt_Status_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (not a target disk).
        /// </summary>
        public static string Txt_Status_NotTargetDisk {
            get {
                return ResourceManager.GetString("Txt_Status_NotTargetDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Txt_Status_Ready {
            get {
                return ResourceManager.GetString("Txt_Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autobackup inactive.
        /// </summary>
        public static string Txt_Status_ReadyWaiting {
            get {
                return ResourceManager.GetString("Txt_Status_ReadyWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (waiting for disk...).
        /// </summary>
        public static string Txt_Status_Waiting {
            get {
                return ResourceManager.GetString("Txt_Status_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chosen: {0}.
        /// </summary>
        public static string Txt_TargetPathChosen {
            get {
                return ResourceManager.GetString("Txt_TargetPathChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD / DVD drive.
        /// </summary>
        public static string Txt_TypeCD {
            get {
                return ResourceManager.GetString("Txt_TypeCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed drive.
        /// </summary>
        public static string Txt_TypeFixed {
            get {
                return ResourceManager.GetString("Txt_TypeFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network drive.
        /// </summary>
        public static string Txt_TypeNetwork {
            get {
                return ResourceManager.GetString("Txt_TypeNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM disk.
        /// </summary>
        public static string Txt_TypeRAM {
            get {
                return ResourceManager.GetString("Txt_TypeRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB drive.
        /// </summary>
        public static string Txt_TypeRemovable {
            get {
                return ResourceManager.GetString("Txt_TypeRemovable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown type.
        /// </summary>
        public static string Txt_TypeUnknown {
            get {
                return ResourceManager.GetString("Txt_TypeUnknown", resourceCulture);
            }
        }
    }
}
